version: '3'

# https://wsvincent.com/django-docker-postgresql/
# see http://blog.innuy.com/2017/07/dockerize-your-django-web-application.html
# http://michal.karzynski.pl/blog/2015/04/19/packaging-django-applications-as-docker-container-images/

services:
  db:
    image: postgres:10.1
    env_file:
      - env_vars.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  nginx:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/code
      - ./config:/etc/nginx/conf.d
    depends_on:
      - django

  django:
    build: .
    command: bash -c "python /code/manage.py migrate --noinput; python manage.py collectstatic --noinput; gunicorn lws.wsgi:application -c ./config/gunicorn.py -b 0.0.0.0:8000"
    volumes:
      - .:/code
    env_file:
      - env_vars.env
    ports:
      - "8000:8000"
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=PostgreSQL
    depends_on:
      - db

volumes:
  postgres_data: