# Generated by Django 2.0.5 on 2018-05-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=100, null=True)),
                ('destination_lat', models.CharField(max_length=15, null=True)),
                ('destination_lng', models.CharField(max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.CharField(max_length=32)),
                ('fcm_token', models.CharField(max_length=32)),
                ('os', models.CharField(choices=[('I', 'iOS'), ('A', 'Android'), ('U', 'Unknown')], default='U', max_length=1)),
                ('info', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
