# Generated by Django 2.1.1 on 2018-09-11 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='info',
        ),
        migrations.RemoveField(
            model_name='device',
            name='mail',
        ),
        migrations.AddField(
            model_name='device',
            name='device',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='idiom',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='platform',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='version',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
