# Generated by Django 2.1.1 on 2018-09-14 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0002_auto_20180914_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='leader',
        ),
        migrations.AddField(
            model_name='alarm',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pager.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
