# Generated by Django 2.1.1 on 2018-09-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0003_auto_20180911_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='os',
        ),
        migrations.AlterField(
            model_name='device',
            name='device',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='idiom',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='platform',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='version',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
