# Generated by Django 2.1.1 on 2018-09-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0004_auto_20180917_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
