# Generated by Django 2.1.1 on 2018-09-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0004_auto_20180911_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
