# Generated by Django 2.1.1 on 2018-09-17 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0005_auto_20180917_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='role',
        ),
        migrations.AddField(
            model_name='membership',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
