# Generated by Django 2.1.1 on 2018-09-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0010_auto_20180926_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='access_key',
            field=models.CharField(default=123, max_length=64),
            preserve_default=False,
        ),
    ]
