# Generated by Django 2.1.1 on 2018-09-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0011_organization_access_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='place',
            field=models.CharField(default=1, max_length=100, verbose_name='Ort'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='plz',
            field=models.CharField(default=1, max_length=5, verbose_name='PLZ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Adresse'),
        ),
    ]
