# Generated by Django 2.1.1 on 2018-09-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0012_add_adress_to_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='fcm_token',
            field=models.CharField(max_length=200),
        ),
    ]
