# Generated by Django 2.1.2 on 2018-10-05 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0013_auto_20180927_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AlterField(
            model_name='device',
            name='fcm_token',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
