# Generated by Django 2.1.2 on 2018-10-05 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0014_auto_20181005_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='idiom',
        ),
    ]
