# Generated by Django 2.1.2 on 2018-10-11 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0016_customuser_organization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='membership',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='members',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
