# Generated by Django 2.1.2 on 2018-10-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0017_remove-membership-table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarm',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='alarm',
            name='debug_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
