# Generated by Django 2.1.3 on 2018-11-12 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pager', '0018_add-debug-response-to-alarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=128, verbose_name='GUID')),
                ('operation_number',
                 models.CharField(blank=True, default='', max_length=20, verbose_name='Operation Nummer')),
                ('alarm_at', models.DateTimeField(verbose_name='Alarmzeit')),
                ('income_at', models.DateTimeField(auto_now_add=True, verbose_name='Alarmeingang')),
                ('messenger', models.CharField(blank=True, default='', max_length=200, verbose_name='Mitteiler')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Kommentar')),
                ('plan', models.CharField(blank=True, default='', max_length=200, verbose_name='Plan')),
                ('priority', models.CharField(blank=True, default='', max_length=100, verbose_name='Priorität')),
                ('debug_response', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-income_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=10, verbose_name='Stichwort')),
                ('emergency_keyword', models.CharField(max_length=10, verbose_name='Schlagwort')),
            ],
        ),
        migrations.CreateModel(
            name='OperationLoop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop', models.CharField(max_length=10, verbose_name='Schleife')),
            ],
        ),
        migrations.CreateModel(
            name='OperationPropertyLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='Location')),
                ('zip_code', models.CharField(blank=True, default='', max_length=5, verbose_name='Postleitzahl')),
                ('city', models.CharField(blank=True, default='', max_length=200, verbose_name='Stadt')),
                ('street', models.CharField(blank=True, default='', max_length=200, verbose_name='Straße')),
                (
                    'street_number',
                    models.CharField(blank=True, default='', max_length=10, verbose_name='Straßennummer')),
                ('intersection', models.CharField(blank=True, default='', max_length=200, verbose_name='Kreuzung')),
                ('geo_latitude',
                 models.DecimalField(decimal_places=12, max_digits=15, null=True, verbose_name='Latitude')),
                ('geo_longitude',
                 models.DecimalField(decimal_places=12, max_digits=15, null=True, verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='OperationResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Name')),
                ('timestamp', models.CharField(blank=True, default='', max_length=200, verbose_name='Timestamp')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pager.Operation')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='einsatzort',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='einsatzort', to='pager.OperationPropertyLocation'),
        ),
        migrations.AddField(
            model_name='operation',
            name='keywords',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='pager.OperationKeywords'),
        ),
        migrations.AddField(
            model_name='operation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pager.Organization'),
        ),
        migrations.AddField(
            model_name='operation',
            name='zielort',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zielort',
                                       to='pager.OperationPropertyLocation'),
        ),
    ]
