# Generated by Django 2.1.3 on 2018-11-12 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0019_auto_20181112_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationloop',
            name='operation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pager.Operation'),
            preserve_default=False,
        ),
    ]
