# Generated by Django 2.1.3 on 2018-11-13 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pager', '0021_auto_20181113_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='income_at',
            new_name='timestamp_income',
        ),
        migrations.RenameField(
            model_name='operation',
            old_name='alarm_at',
            new_name='timestamp',
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['-timestamp']},
        ),
    ]
