# Generated by Django 2.1.3 on 2018-11-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0022_auto_20181113_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarm',
            name='organization',
        ),
        migrations.AlterField(
            model_name='operationpropertylocation',
            name='geo_latitude',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=42, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='operationpropertylocation',
            name='geo_longitude',
            field=models.DecimalField(blank=True, decimal_places=30, max_digits=42, null=True, verbose_name='Longitude'),
        ),
        migrations.DeleteModel(
            name='Alarm',
        ),
    ]
