# Generated by Django 2.1.3 on 2018-11-22 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pager', '0023_auto_20181122_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='push_message',
            field=models.TextField(default='Einsatz vom {{ Timestamp }} (Einsatzzeitpunkt)\nStichwörter: {{ Keywords }}\nHinweis: {{ Comment }}\n\nEinsatzort: {{ Einsatzort }}\nFahrzeuge:\n{% for Resource in Resources %}\n    {{ Resource }}\n{% endfor %}\n', verbose_name='Nachricht'),
        ),
        migrations.AddField(
            model_name='organization',
            name='push_title',
            field=models.CharField(default='{{ Keywords.EmergencyKeyword }} - {{ Keywords.Keyword }}', max_length=255, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='operationkeywords',
            name='emergency_keyword',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Stichwort'),
        ),
        migrations.AlterField(
            model_name='operationkeywords',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Schlagwort'),
        ),
    ]
